interface/craco.config.js
interface/src/pages/Pool/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/44)

fix: eSpace pool blockNumber directly fetch fullnode

---

interface/src/hooks/useController.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/45)

fix: eSpace ethers use provider insteadof signer

---

contract/.gitignore
contract/scripts/snapshotPoSPool.js

FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/47)

Add PoS staker snapshot script

---

contract/contracts/eSpace/CoreBridge.sol

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/53)

add one method in CoreBridge to withdraw part votes

---

contract/bin/pool.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/55)

add command

---

contract/service/eSpacePoolStatusSyncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/56)

update eSpace pool sync logic

---

contract/service/eSpacePoolStatusSyncer.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/57)

Opwithdraw

---

contract/.env.example

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/62)

ForceRetired need parameter POS_NODE_ADDRESS

---

contract/CHANGELOG.md
contract/contracts/PoSPool.sol
contract/package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/63)

Pos unlock update

---

contract/.gitignore
contract/CHANGELOG.md
contract/bin/pool.js
contract/contracts/PoSPool.sol
contract/docs/HowToReplacePosKeyZH.md
contract/hardhat.config.js
contract/scripts/conflux.js
contract/scripts/replaceKey/reLockAllVotes.js
contract/scripts/replaceKey/unlockAllVotes.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/64)

Register bug fix 

---

interface/package.json
interface/postcss.config.cjs
interface/src/pages/Home/index.js
interface/src/pages/Pool/ConfirmModal.js
interface/src/pages/Pool/Header.js
interface/src/pages/Pool/index.js
interface/src/pages/components/Header/index.js

增加pos pool移动端适配
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/67)

Add pos pool mobile adaptation

---

contract/gov_pools.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/76)

add phx v1

---

contract/gov_pools.json

Webomatic PoS pool was updated to official pos pool v1.3 smart contracts. Also UI has been updated to reflect the update - to support governance locking information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/80)

Added Webomatic PoS pool info to gov_pools.json

---

contract/gov_pools.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/84)

add one espace pool that can participate governance

---

interface/src/pages/Pool/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/85)

fix: add gasPrice to core

---

contract/CHANGELOG.md
contract/contracts/VotingEscrow.sol
contract/contracts/eSpacePoolBridge.sol

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/86)

change governance topic count

---

contract/contracts/eSpacePoolBridge.sol

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/87)

format bridge solidity code

---

interface/craco.config.js
interface/package.json
interface/src/hooks/useIsNetworkMatch.js
interface/src/hooks/useWallet.js
interface/src/index.js
interface/src/pages/Pool/index.js
interface/yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/88)

fix: Init problem caused by fluent upgrade to mv3

---

contract/CHANGELOG.md
contract/contracts/PoSPool.sol

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/92)

add a separate manager role to core space PoSPool contract

---

contract/contracts/eSpace/eSpacePoSPool.sol
contract/contracts/eSpacePoolBridge.sol
contract/contracts/utils/PoSPoolBatchCall.sol
contract/scripts/core/03_deploy_eSpacePoolBridge.js
contract/service/eSpacePoolStatusSyncer.js
contract/test/espace-pool-test.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/93)

fix espace reward decrease issue

---

contract/gov_pools.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/conflux-fans/pos-pool/94)

Add STC to gov pools
